"""Add remaining RBAC linking tables and columns using batch mode

Revision ID: 3f9efe8a42d2
Revises: 20260329_000005
Create Date: 2026-03-29 23:01:55.353301
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f9efe8a42d2"
down_revision: Union[str, Sequence[str], None] = "20260329_000005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "role_permissions" not in existing_tables:
        op.create_table(
            "role_permissions",
            sa.Column("role_id", sa.Integer(), nullable=False),
            sa.Column("permission_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["permission_id"],
                ["permissions.id"],
                name=op.f("fk_role_permissions_permission_id"),
            ),
            sa.ForeignKeyConstraint(
                ["role_id"], ["rbac.id"], name=op.f("fk_role_permissions_role_id")
            ),
            sa.PrimaryKeyConstraint(
                "role_id", "permission_id", name=op.f("pk_role_permissions")
            ),
        )
    if "user_permissions" not in existing_tables:
        op.create_table(
            "user_permissions",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("permission_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["permission_id"],
                ["permissions.id"],
                name=op.f("fk_user_permissions_permission_id"),
            ),
            sa.ForeignKeyConstraint(
                ["user_id"], ["users.id"], name=op.f("fk_user_permissions_user_id")
            ),
            sa.PrimaryKeyConstraint(
                "user_id", "permission_id", name=op.f("pk_user_permissions")
            ),
        )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("description_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_permissions_title_id"),
            "translations_small",
            ["title_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_permissions_description_id"),
            "translations_small",
            ["description_id"],
            ["id"],
        )
        batch_op.drop_column("title_key")
        batch_op.drop_column("description_key")

    with op.batch_alter_table("rbac", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("description_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_rbac_permissions_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rbac_description_id"),
            "translations_small",
            ["description_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rbac_title_id"), "translations_small", ["title_id"], ["id"]
        )
        batch_op.drop_column("permissions_id")
        batch_op.drop_column("title_key")
        batch_op.drop_column("description_key")

    with op.batch_alter_table("translations_huge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_translations_huge_lookup"))
        batch_op.create_unique_constraint(
            "uq_translations_huge_key_language", ["key", "language_code"]
        )

    with op.batch_alter_table("translations_large", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_translations_large_lookup"))
        batch_op.create_unique_constraint(
            "uq_translations_large_key_language", ["key", "language_code"]
        )

    with op.batch_alter_table("translations_medium", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_translations_medium_lookup"))
        batch_op.create_unique_constraint(
            "uq_translations_medium_key_language", ["key", "language_code"]
        )

    with op.batch_alter_table("translations_small", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_translations_small_lookup"))
        batch_op.create_unique_constraint(
            "uq_translations_small_key_language", ["key", "language_code"]
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column("role_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_users_uuid"), ["uuid"], unique=True)
        batch_op.create_foreign_key(
            batch_op.f("fk_users_role_id"), "rbac", ["role_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_users_role_id"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_users_uuid"))
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )
        batch_op.drop_column("role_id")
        batch_op.drop_column("uuid")

    with op.batch_alter_table("translations_small", schema=None) as batch_op:
        batch_op.drop_constraint("uq_translations_small_key_language", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_translations_small_lookup"),
            ["key", "language_code"],
            unique=False,
        )

    with op.batch_alter_table("translations_medium", schema=None) as batch_op:
        batch_op.drop_constraint("uq_translations_medium_key_language", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_translations_medium_lookup"),
            ["key", "language_code"],
            unique=False,
        )

    with op.batch_alter_table("translations_large", schema=None) as batch_op:
        batch_op.drop_constraint("uq_translations_large_key_language", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_translations_large_lookup"),
            ["key", "language_code"],
            unique=False,
        )

    with op.batch_alter_table("translations_huge", schema=None) as batch_op:
        batch_op.drop_constraint("uq_translations_huge_key_language", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_translations_huge_lookup"),
            ["key", "language_code"],
            unique=False,
        )

    with op.batch_alter_table("rbac", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description_key", sa.VARCHAR(length=128), nullable=False)
        )
        batch_op.add_column(
            sa.Column("title_key", sa.VARCHAR(length=128), nullable=False)
        )
        batch_op.add_column(sa.Column("permissions_id", sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f("fk_rbac_title_id"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_rbac_description_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_rbac_permissions_id"),
            "permissions",
            ["permissions_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("description_id")
        batch_op.drop_column("title_id")

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description_key", sa.VARCHAR(length=128), nullable=False)
        )
        batch_op.add_column(
            sa.Column("title_key", sa.VARCHAR(length=128), nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_permissions_description_id"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_permissions_title_id"), type_="foreignkey"
        )
        batch_op.drop_column("description_id")
        batch_op.drop_column("title_id")

    op.create_table(
        "_alembic_tmp_permissions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("name", name=op.f("uq_permissions_name")),
    )
    op.drop_table("user_permissions")
    op.drop_table("role_permissions")
    # ### end Alembic commands ###
